import { Translation, ElectricityTariff } from './types';

export const translations: Record<'ar' | 'en', Translation> = {
  ar: {
    title: "ليرتنا",
    subtitle: "محول العملات السورية وأسعار الصرف اللحظية",
    home: "الرئيسية",
    services: "الخدمات",
    converter: "محول العملات",
    calculator: "حاسبة الباقي",
    newToOld: "من جديد إلى قديم",
    oldToNew: "من قديم إلى جديد",
    amount: "المبلغ",
    result: "النتيجة",
    newLira: "ليرة جديدة",
    oldLira: "ليرة قديمة",
    totalPrice: "السعر الإجمالي",
    amountPaid: "المبلغ المدفوع",
    changeNeeded: "الباقي المستحق",
    denominations: "الفئات النقدية",
    calculate: "احسب",
    reset: "إعادة تعيين",
    marketRates: "أسعار الصرف الحية",
    loading: "جاري التحميل...",
    notes: "ملاحظات",
    cbs: "المصرف المركزي",
    blackMarket: "السوق السوداء",
    buy: "شراء",
    sell: "مبيع",
    lastUpdate: "آخر تحديث",
    from: "من",
    to: "إلى",
    aboutUs: "من نحن",
    privacyPolicy: "سياسة الخصوصية",
    contactUs: "اتصل بنا",
    aboutContent: "موقع ليرتنا هو منصة مستقلة تهدف لتسهيل العمليات المالية للمواطن السوري عبر توفير أدوات تحويل دقيقة بين فئات العملة القديمة والجديدة ومتابعة أسعار الصرف العالمية.",
    privacyContent: "نحن نحترم خصوصيتك. لا نقوم بجمع أي بيانات شخصية أو مالية حساسة. جميع الحسابات تتم محلياً في متصفحك.",
    contactContent: "يسعدنا تواصلكم معنا عبر منصات التواصل الاجتماعي الرسمية الموضحة أدناه لأي استفسار أو اقتراح.",
    downloadApp: "حمل التطبيق الآن",
    directDownload: "تحميل مباشر",
    appNote: "تجربة أفضل وأسرع على هاتفك المحمول.",
    rateError: "تعذر تحميل الأسعار الحية. قد تكون هناك مشكلة في الشبكة أو في الخادم المصدر. يرجى المحاولة مرة أخرى لاحقاً.",
    electricityCalculator: "حاسبة فاتورة الكهرباء",
    consumption: "الاستهلاك",
    kwh: "كيلو واط ساعي",
    subscriptionType: "نوع الاشتراك",
    billDetails: "تفاصيل الفاتورة",
    tier: "شريحة",
    rate: "تعرفة",
    cost: "التكلفة",
    totalBill: "إجمالي الفاتورة",
    syp: "ل.س",
  },
  en: {
    title: "Liratna",
    subtitle: "Syrian Currency Converter & Live Exchange Rates",
    home: "Home",
    services: "Services",
    converter: "Currency Converter",
    calculator: "Change Calculator",
    newToOld: "New to Old",
    oldToNew: "Old to New",
    amount: "Amount",
    result: "Result",
    newLira: "New Lira",
    oldLira: "Old Lira",
    totalPrice: "Total Price",
    amountPaid: "Amount Paid",
    changeNeeded: "Change Needed",
    denominations: "Denominations",
    calculate: "Calculate",
    reset: "Reset",
    marketRates: "Live Exchange Rates",
    loading: "Loading...",
    notes: "Notes",
    cbs: "Central Bank",
    blackMarket: "Black Market",
    buy: "Buy",
    sell: "Sell",
    lastUpdate: "Last Update",
    from: "From",
    to: "To",
    aboutUs: "About Us",
    privacyPolicy: "Privacy Policy",
    contactUs: "Contact Us",
    aboutContent: "Liratna is an independent platform aimed at facilitating financial operations for Syrian citizens by providing accurate conversion tools between old and new currency denominations.",
    privacyContent: "We respect your privacy. We do not collect any sensitive personal or financial data. All calculations are done locally in your browser.",
    contactContent: "We are happy to connect with you through our official social media platforms listed below for any inquiries or suggestions.",
    downloadApp: "Download The App",
    directDownload: "Direct Download",
    appNote: "A better and faster experience on your mobile phone.",
    rateError: "Could not load live rates. There might be a network issue or a problem with the source server. Please try again later.",
    electricityCalculator: "Electricity Bill Calculator",
    consumption: "Consumption",
    kwh: "kWh",
    subscriptionType: "Subscription Type",
    billDetails: "Bill Details",
    tier: "Tier",
    rate: "Rate",
    cost: "Cost",
    totalBill: "Total Bill",
    syp: "SYP",
  }
};

export const ELECTRICITY_TARIFFS: ElectricityTariff[] = [
  {
    id: 'household',
    name: { ar: 'منزلي', en: 'Household' },
    type: 'tiered',
    tiers: [
      { limit: 300, price: 600 },
      { limit: null, price: 1400 }, // null limit means "and above"
    ]
  },
  { id: 'commercial', name: { ar: 'تجاري', en: 'Commercial' }, type: 'flat', rate: 1400 },
  { id: 'billboards', name: { ar: 'لوحات إعلان', en: 'Billboards' }, type: 'flat', rate: 1800 },
  { id: 'charity', name: { ar: 'جمعيات خيرية', en: 'Charities' }, type: 'flat', rate: 1400 },
  { id: 'worship', name: { ar: 'دور عبادة', en: 'Places of Worship' }, type: 'flat', rate: 1400 },
  { id: 'tourism', name: { ar: 'سياحي', en: 'Tourism' }, type: 'flat', rate: 1400 },
  { id: 'research', name: { ar: 'بحوث علمية', en: 'Scientific Research' }, type: 'flat', rate: 1400 },
  { id: 'official', name: { ar: 'دوائر رسمية', en: 'Official Depts.' }, type: 'flat', rate: 1400 },
  { id: 'public_lighting', name: { ar: 'إنارة عامة', en: 'Public Lighting' }, type: 'flat', rate: 1400 },
  { id: 'public_hospital', name: { ar: 'مشفى عام', en: 'Public Hospital' }, type: 'flat', rate: 1400 },
  { id: 'industrial', name: { ar: 'صناعي', en: 'Industrial' }, type: 'flat', rate: 1400 },
  { id: 'agricultural', name: { ar: 'زراعي', en: 'Agricultural' }, type: 'flat', rate: 1400 },
];

export const MAINTENANCE_MESSAGES: string[] = [
  "نحن نعمل على تحسين تجربتكم. سنعود قريباً.",
  "نقوم ببعض التحديثات الهامة. شكراً لصبركم.",
  "الموقع في استراحة قصيرة للتحسينات. نراكم بعد قليل!",
  "نعتذر عن الإزعاج، الصيانة ضرورية لخدمتكم بشكل أفضل.",
  "خبراؤنا يعملون الآن لجعل الموقع أسرع وأفضل.",
  "لحظات ونعود بنسخة محسنة. شكراً لتفهمكم.",
  "تحديثات جديدة في الطريق! الموقع سيعود للعمل قريباً.",
  "نحن نعتني ببعض الأمور التقنية. لن نطيل الغياب.",
  "صيانة دورية لضمان أفضل أداء. نقدر انتظاركم.",
  "الموقع غير متاح مؤقتاً. نعمل على إعادة الخدمة بأسرع وقت.",
  "نقوم بترقية خوادمنا لخدمة أسرع. دقائق ونعود.",
  "استراحة محارب! نعود قريباً بميزات جديدة.",
  "بعض السحر يحدث في الكواليس. ترقبوا!",
  "نحن نُلمّع كل زاوية في الموقع. انتظرونا.",
  "التطوير مستمر، والصيانة جزء منه. شكراً لثقتكم.",
  "نعمل على إصلاح بعض الأعطال الصغيرة. لن نتأخر.",
  "نعتذر، الموقع في وضع الصيانة المجدولة.",
  "تحسينات أمنية قيد التنفيذ. أمانكم أولويتنا.",
  "نحن نجهز لكم مفاجآت! انتظرونا قليلاً.",
  "الموقع يعود بعد قليل بحلة جديدة وأداء أقوى.",
  "فنجان قهوة ونعود. شكراً على صبركم الجميل."
];