import { Translation, ElectricityTariff } from './types';

export const translations: Record<'ar' | 'en', Translation> = {
  ar: {
    title: "ليرتنا",
    subtitle: "محول العملات السورية وأسعار الصرف اللحظية",
    home: "الرئيسية",
    services: "الخدمات",
    converter: "محول العملات",
    calculator: "حاسبة الباقي",
    newToOld: "من جديد إلى قديم",
    oldToNew: "من قديم إلى جديد",
    amount: "المبلغ",
    result: "النتيجة",
    newLira: "ليرة جديدة",
    oldLira: "ليرة قديمة",
    totalPrice: "السعر الإجمالي",
    amountPaid: "المبلغ المدفوع",
    changeNeeded: "الباقي المستحق",
    denominations: "الفئات النقدية",
    calculate: "احسب",
    reset: "إعادة تعيين",
    marketRates: "أسعار الصرف الحية",
    loading: "جاري التحميل...",
    notes: "ملاحظات",
    cbs: "المصرف المركزي",
    blackMarket: "السوق السوداء",
    buy: "شراء",
    sell: "مبيع",
    lastUpdate: "آخر تحديث",
    from: "من",
    to: "إلى",
    aboutUs: "من نحن",
    privacyPolicy: "سياسة الخصوصية",
    contactUs: "اتصل بنا",
    aboutContent: "موقع ليرتنا هو منصة مستقلة تهدف لتسهيل العمليات المالية للمواطن السوري عبر توفير أدوات تحويل دقيقة بين فئات العملة القديمة والجديدة ومتابعة أسعار الصرف العالمية.",
    privacyTitle: "سياسة الخصوصية",
    privacyContent: [
      "في ليرتنا، خصوصيتك هي أولويتنا القصوى. تم تصميم هذه السياسة لمساعدتك على فهم كيفية تعاملنا مع البيانات.",
      "نحن لا نجمع أو نخزن أي معلومات تعريف شخصية (PII) من زوارنا. جميع الأدوات المتاحة على موقعنا، مثل محول العملات وحاسبة الباقي، تعمل بالكامل على جهازك (من جانب العميل). هذا يعني أن أي أرقام تدخلها لا تترك متصفحك أبداً ولا يتم إرسالها إلى خوادمنا.",
      "نستخدم خدمة تحليلات بسيطة (Supabase Analytics) لفهم كيفية استخدام موقعنا بشكل عام، مثل عدد الزيارات ونوع الأدوات المستخدمة. هذه البيانات مجهولة تماماً ولا ترتبط بأي فرد. هدفها الوحيد هو تحسين خدماتنا.",
      "لا نستخدم ملفات تعريف الارتباط (Cookies) لتتبعك عبر الإنترنت. قد يتم استخدام التخزين المحلي في متصفحك لحفظ تفضيلاتك، مثل اللغة أو المظهر المختار، لتحسين تجربتك عند العودة للموقع.",
      "نحن لا نشارك أي بيانات مع أطراف ثالثة، لأننا ببساطة لا نجمع أي بيانات شخصية لمشاركتها.",
      "قد يتم تحديث هذه السياسة من وقت لآخر. سنقوم بنشر أي تغييرات على هذه الصفحة."
    ],
    contactTitle: "اتصل بنا",
    contactContent: [
        "يسعدنا دائماً الاستماع إليك! سواء كان لديك سؤال، أو اقتراح لتحسين خدماتنا، أو ترغب فقط في إلقاء التحية، فإننا نرحب بتواصلك.",
        "أفضل وأسرع طريقة للتواصل معنا هي عبر منصات التواصل الاجتماعي الرسمية. فريقنا متواجد للرد على استفساراتكم وتقديم الدعم اللازم.",
        "يمكنك العثور على روابط مباشرة إلى صفحاتنا على فيسبوك، تيليجرام، واتساب، وإنستغرام في الصفحة الرئيسية للموقع. انقر على الأيقونة المناسبة للوصول إلينا.",
        "نحن نقدر ملاحظاتك ونعتبرها جزءاً أساسياً من تطوير منصة ليرتنا لتلبية احتياجاتكم بشكل أفضل."
    ],
    downloadApp: "حمل التطبيق الآن",
    directDownload: "تحميل مباشر",
    appNote: "تجربة أفضل وأسرع على هاتفك المحمول.",
    rateError: "تعذر تحميل الأسعار الحية. قد تكون هناك مشكلة في الشبكة أو في الخادم المصدر. يرجى المحاولة مرة أخرى لاحقاً.",
    electricityCalculator: "حاسبة فاتورة الكهرباء",
    consumption: "الاستهلاك",
    kwh: "كيلو واط ساعي",
    subscriptionType: "نوع الاشتراك",
    billDetails: "تفاصيل الفاتورة",
    tier: "شريحة",
    rate: "تعرفة",
    cost: "التكلفة",
    totalBill: "إجمالي الفاتورة",
    syp: "ل.س",
  },
  en: {
    title: "Liratna",
    subtitle: "Syrian Currency Converter & Live Exchange Rates",
    home: "Home",
    services: "Services",
    converter: "Currency Converter",
    calculator: "Change Calculator",
    newToOld: "New to Old",
    oldToNew: "Old to New",
    amount: "Amount",
    result: "Result",
    newLira: "New Lira",
    oldLira: "Old Lira",
    totalPrice: "Total Price",
    amountPaid: "Amount Paid",
    changeNeeded: "Change Needed",
    denominations: "Denominations",
    calculate: "Calculate",
    reset: "Reset",
    marketRates: "Live Exchange Rates",
    loading: "Loading...",
    notes: "Notes",
    cbs: "Central Bank",
    blackMarket: "Black Market",
    buy: "Buy",
    sell: "Sell",
    lastUpdate: "Last Update",
    from: "From",
    to: "To",
    aboutUs: "About Us",
    privacyPolicy: "Privacy Policy",
    contactUs: "Contact Us",
    aboutContent: "Liratna is an independent platform aimed at facilitating financial operations for Syrian citizens by providing accurate conversion tools between old and new currency denominations.",
    privacyTitle: "Privacy Policy",
    privacyContent: [
        "At Liratna, your privacy is our top priority. This policy is designed to help you understand how we handle data.",
        "We do not collect or store any Personally Identifiable Information (PII) from our visitors. All tools on our site, such as the currency converter and change calculator, operate entirely on your device (client-side). This means any numbers you enter never leave your browser and are not sent to our servers.",
        "We use a simple analytics service (Supabase Analytics) to understand how our site is used in general, such as the number of visits and which tools are popular. This data is completely anonymous and not linked to any individual. Its sole purpose is to improve our services.",
        "We do not use cookies to track you online. Your browser's local storage may be used to save your preferences, like your chosen language or theme, to enhance your experience on return visits.",
        "We do not share any data with third parties because we simply do not collect any personal data to share.",
        "This policy may be updated from time to time. We will post any changes on this page."
    ],
    contactTitle: "Contact Us",
    contactContent: [
        "We are always happy to hear from you! Whether you have a question, a suggestion to improve our services, or just want to say hello, we welcome your communication.",
        "The best and fastest way to reach us is through our official social media platforms. Our team is available to answer your inquiries and provide necessary support.",
        "You can find direct links to our Facebook, Telegram, WhatsApp, and Instagram pages on the website's homepage. Click on the appropriate icon to get in touch.",
        "We value your feedback and consider it an essential part of developing the Liratna platform to better meet your needs."
    ],
    downloadApp: "Download The App",
    directDownload: "Direct Download",
    appNote: "A better and faster experience on your mobile phone.",
    rateError: "Could not load live rates. There might be a network issue or a problem with the source server. Please try again later.",
    electricityCalculator: "Electricity Bill Calculator",
    consumption: "Consumption",
    kwh: "kWh",
    subscriptionType: "Subscription Type",
    billDetails: "Bill Details",
    tier: "Tier",
    rate: "Rate",
    cost: "Cost",
    totalBill: "Total Bill",
    syp: "SYP",
  }
};

export const ELECTRICITY_TARIFFS: ElectricityTariff[] = [
  {
    id: 'household',
    name: { ar: 'منزلي', en: 'Household' },
    type: 'tiered',
    tiers: [
      { limit: 300, price: 600 },
      { limit: null, price: 1400 }, // null limit means "and above"
    ]
  },
  { id: 'commercial', name: { ar: 'تجاري', en: 'Commercial' }, type: 'flat', rate: 1400 },
  { id: 'billboards', name: { ar: 'لوحات إعلان', en: 'Billboards' }, type: 'flat', rate: 1800 },
  { id: 'charity', name: { ar: 'جمعيات خيرية', en: 'Charities' }, type: 'flat', rate: 1400 },
  { id: 'worship', name: { ar: 'دور عبادة', en: 'Places of Worship' }, type: 'flat', rate: 1400 },
  { id: 'tourism', name: { ar: 'سياحي', en: 'Tourism' }, type: 'flat', rate: 1400 },
  { id: 'research', name: { ar: 'بحوث علمية', en: 'Scientific Research' }, type: 'flat', rate: 1400 },
  { id: 'official', name: { ar: 'دوائر رسمية', en: 'Official Depts.' }, type: 'flat', rate: 1400 },
  { id: 'public_lighting', name: { ar: 'إنارة عامة', en: 'Public Lighting' }, type: 'flat', rate: 1400 },
  { id: 'public_hospital', name: { ar: 'مشفى عام', en: 'Public Hospital' }, type: 'flat', rate: 1400 },
  { id: 'industrial', name: { ar: 'صناعي', en: 'Industrial' }, type: 'flat', rate: 1400 },
  { id: 'agricultural', name: { ar: 'زراعي', en: 'Agricultural' }, type: 'flat', rate: 1400 },
];

export const MAINTENANCE_MESSAGES: string[] = [
  "نحن نعمل على تحسين تجربتكم. سنعود قريباً.",
  "نقوم ببعض التحديثات الهامة. شكراً لصبركم.",
  "الموقع في استراحة قصيرة للتحسينات. نراكم بعد قليل!",
  "نعتذر عن الإزعاج، الصيانة ضرورية لخدمتكم بشكل أفضل.",
  "خبراؤنا يعملون الآن لجعل الموقع أسرع وأفضل.",
  "لحظات ونعود بنسخة محسنة. شكراً لتفهمكم.",
  "تحديثات جديدة في الطريق! الموقع سيعود للعمل قريباً.",
  "نحن نعتني ببعض الأمور التقنية. لن نطيل الغياب.",
  "صيانة دورية لضمان أفضل أداء. نقدر انتظاركم.",
  "الموقع غير متاح مؤقتاً. نعمل على إعادة الخدمة بأسرع وقت.",
  "نقوم بترقية خوادمنا لخدمة أسرع. دقائق ونعود.",
  "استراحة محارب! نعود قريباً بميزات جديدة.",
  "بعض السحر يحدث في الكواليس. ترقبوا!",
  "نحن نُلمّع كل زاوية في الموقع. انتظرونا.",
  "التطوير مستمر، والصيانة جزء منه. شكراً لثقتكم.",
  "نعمل على إصلاح بعض الأعطال الصغيرة. لن نتأخر.",
  "نعتذر، الموقع في وضع الصيانة المجدولة.",
  "تحسينات أمنية قيد التنفيذ. أمانكم أولويتنا.",
  "نحن نجهز لكم مفاجآت! انتظرونا قليلاً.",
  "الموقع يعود بعد قليل بحلة جديدة وأداء أقوى.",
  "فنجان قهوة ونعود. شكراً على صبركم الجميل."
];